source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'just-the-docs', '~> 0.7.0'
gem 'webrick', '~> 1.8'

# GitHub Pages plugins
group :jekyll_plugins do
  gem 'jekyll-remote-theme'
  gem 'jekyll-seo-tag'
end
